name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:

  build:

    runs-on: [ubuntu-latest, ubuntu-18.04]

    steps:
    - uses: actions/checkout@main
    - name: Build the Docker image
      run: docker build . --file scraper.Dockerfile --tag scraper:$(date +%s)
